version: "3.2"

services: 

    api:
        build:
            context: ./api
        depends_on:
            - sql
        networks:
            - backend
        environment:
            - MYSQL_HOST=sql
            - MYSQL_USER=root
            - MYSQL_PASS=root
        volumes:
            - ./dynamic:/dynamic/
            - ./static:/static/
        ports:
            - "80:80"
        container_name: onitun-api

    sql:
        image: mysql:5
        networks:
            - backend
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=onielltunnel
        volumes:
            - ./sqldata/:/var/lib/mysql
            - ./sqlinit/:/docker-entrypoint-initdb.d
        security_opt:
            - seccomp:unconfined
        container_name: onitun-sql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - sql
        networks:
            - backend
        ports:
            - "1337:80"
        environment:
            - PMA_HOST=sql
            - PMA_PORT=3306
        container_name: onitun-pma

networks:
    backend: